---
name: "CICD Nautobot NV Data Models"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
      - "dev"
      - "ltm-*"
    tags:
      - "v*"
  pull_request: ~

jobs:
  ruff:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Install uv"
        uses: "astral-sh/setup-uv@v5"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: "Setup environment"
        run: uv sync --all-extras
      - name: "Linting: ruff"
        run: uv run invoke ruff
      - name: "Prune uv cache"
        run: uv cache prune --ci

  yamllint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Install uv"
        uses: "astral-sh/setup-uv@v5"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: "Setup environment"
        run: uv sync --all-extras
      - name: "Linting: yamllint"
        run: uv run invoke yamllint
      - name: "Prune uv cache"
        run: uv cache prune --ci

  uv-lock:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Install uv"
        uses: "astral-sh/setup-uv@v5"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: "Setup environment"
        run: uv sync --all-extras
      - name: "Check: uv lock"
        run: uv run invoke lock --check
      - name: "Prune uv cache"
        run: uv cache prune --ci

  unittests:
    needs:
      - "ruff"
      - "yamllint"
      - "uv-lock"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Install uv"
        uses: "astral-sh/setup-uv@v5"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: "Setup environment"
        run: uv sync --all-extras
      - name: "Check migrations"
        run: uv run invoke check-migrations
      - name: "Run unit tests"
        run: uv run invoke unittest --failfast
      - name: "Run coverage"
        run: uv run invoke unittest-coverage
      - name: "Prune uv cache"
        run: uv cache prune --ci
